C:\Users\BRAHMAJI\Desktop\All data\porfolio> git status  On branch main  Your branch and 'origin/main' have diverged,  and have 4 and 13 different commits each, respectively.    (use "git pull" if you want to integrate the remote branch with    yours)
   Changes not staged for commit:
     (use "git add/rm <file>..." to update what will be committed)
       (use "git restore <file>..." to discard changes in working
       directory)
               modified:   index.html
	               deleted:    portfolio.html
		               deleted:    profile.png
			               modified:   style.css

				       Untracked files:
				               Img.jpg
					       no changes added to
					       commit (use "git add"
					       and/or "git commit -a")
					       PS
					       C:\Users\BRAHMAJI\Desktop\All
					       data\porfolio> git add .
					       warning: in the working
					       copy of 'style.css', LF
					       will be replaced by CRLF
					       the next time Git touches
					       it
					       PS
					       C:\Users\BRAHMAJI\Desktop\All
					       data\porfolio> git commit
					       -m "Updated portfolio
					       content and fixed HTML
					       errors"
					       [main 2e2047d] Updated
					       portfolio content and
					       fixed HTML errors
					        create mode 100644
						Img.jpg
						 delete mode 100644
						 portfolio.html
						  delete mode 100644
						  profile.png
						  PS
						  C:\Users\BRAHMAJI\Desktop\All
						  data\porfolio> git
						  push origin main
						  To
						  https://github.com/Jaga788/Portfolio.git
						   ! [rejected]
						   main -> main
						   (non-fast-forward)
						   error: failed to push
						   some refs to
						   'https://github.com/Jaga788/Portfolio.git'
						   hint: its remote
						   counterpart. If you
						   want to integrate the
						   remote changes,
						   hint: use 'git pull'
						   before pushing again.
						   hint: See the 'Note
						   about fast-forwards'
						   in 'git push --help'
						   for details.
						   PS
						   C:\Users\BRAHMAJI\Desktop\All
						   data\porfolio> git
						   pull origin main
						   --rebase
						   From
						   https://github.com/Jaga788/Portfolio
						    * branch
						      main       ->
						      FETCH_HEAD
						      Auto-merging
						      index.html
						      CONFLICT
						      (content): Merge
						      conflict in
						      index.html
						      Auto-merging
						      style.css
						      CONFLICT
						      (content): Merge
						      conflict in
						      style.css
						      error: could not
						      apply 5630c83...
						      update files
						      hint: Resolve all
						      conflicts
						      manually, mark
						      them as resolved
						      with
						      hint: "git add/rm
						      <conflicted_files>",
						      then run "git
						      rebase
						      --continue".
						      hint: Disable this
						      message with "git
						      config set
						      advice.mergeConflict
						      false"
						      update files

						      # Conflicts:
						      #       index.html
						      #       style.css

						      # Please enter the
						      commit message for
						      your changes.
						      Lines starting
						      # with '#' will be
						      ignored, and an
						      empty message
						      aborts the commit.
						      #
						      # interactive
						      rebase in
						      progress; onto
						      f2e1856
						      # Last command
						      done (1 command
						      done):
						      #    pick 5630c83
						      update files
						      # Next command to
						      do (1 remaining
						      command):
						      #    pick 2e2047d
						      Updated portfolio
						      content and fixed
						      HTML errors
						      # You are
						      currently rebasing
						      branch 'main' on
						      'f2e1856'.
						      #
						      # Changes to be
						      committed:
						      #       modified:
						      index.html
						      #       modified:
						      style.css
On branch main
Your branch and 'origin/main' have diverged,
and have 4 and 13 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   index.html
        deleted:    portfolio.html
        deleted:    profile.png
        modified:   style.css

Untracked files:
        Img.jpg
no changes added to commit (use "git add" and/or "git commit -a")
PS C:\Users\BRAHMAJI\Desktop\All data\porfolio> git add .
warning: in the working copy of 'style.css', LF will be replaced by CRLF the next time Git touches it
PS C:\Users\BRAHMAJI\Desktop\All data\porfolio> git commit -m "Updated portfolio content and fixed HTML errors"
[main 2e2047d] Updated portfolio content and fixed HTML errors
 create mode 100644 Img.jpg
 delete mode 100644 portfolio.html
 delete mode 100644 profile.png
PS C:\Users\BRAHMAJI\Desktop\All data\porfolio> git push origin main
To https://github.com/Jaga788/Portfolio.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Jaga788/Portfolio.git'
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\BRAHMAJI\Desktop\All data\porfolio> git pull origin main --rebase
From https://github.com/Jaga788/Portfolio
 * branch            main       -> FETCH_HEAD
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Auto-merging style.css
CONFLICT (content): Merge conflict in style.css
error: could not apply 5630c83... update files
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: Disable this message with "git config set advice.mergeConflict false"
update files